TrackTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: track-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: status
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: status
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: track_id
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: track_status
        KeySchema:
          - AttributeName: status
            KeyType: HASH
        Projection:
          ProjectionType: ALL
  DeletionPolicy: Delete