TrackTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: track-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: status
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: status
        KeyType: RANGE
  DeletionPolicy: Delete