service: track-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    TRACK_TABLE_NAME: ${self:custom.TrackTable.name}
    TRACK_DISPATCH_SQS_NAME: ${self:custom.DispatchTrackSQS.name}
    TRACK_DISPATCH_SQS_DELAY: 30
  iamRoleStatements:
    - ${file(iam/TrackTableIAM.yml):TrackTableIAM}
    - ${file(iam/TrackSQSIAM.yml):TrackSQSIAM}

resources:
  Resources:
    TrackTable: ${file(resources/TrackTable.yml):TrackTable}
    DispatchTrackSQS: ${file(resources/DispatchTrackSQS.yml):DispatchTrackSQS}

functions:
  createTrack:
    handler: src/handlers/createTrack.handler
    events:
      - http:
          method: POST
          path: /track
          cors: true
          authorizer: ${self:custom.authorizer}

  getTrackById:
    handler: src/handlers/getTrackById.handler
    events:
      - http:
          method: GET
          path: /track/{id}
          cors: true
          authorizer: ${self:custom.authorizer}

  dispatchTrack:
    handler: src/handlers/dispatchTrack.handler
    events:
      - sqs:
          arn: ${self:custom.DispatchTrackSQS.arn}

  finishTrack:
    handler: src/handlers/finishTrack.handler
    events:
      - schedule: rate(1 minute)

custom:
  TrackTable:
    name: !Ref TrackTable
    arn: !GetAtt TrackTable.Arn
  DispatchTrackSQS:
    name: !Ref DispatchTrackSQS
    arn: !GetAtt DispatchTrackSQS.Arn
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-${self:provider.stage}-auth
  bundle:
    linting: false